spring:
    application:
        name: roomsApp
    profiles:
        active: dev

    jpa:
        database: mysql
        properties:
            javax.persistance.sharedCache.mode: ALL
            hibernate.dialect: org.hibernate.dialect.MySQLDialect
            hibernate.use_second_level_cache: true
            hibernate.user_query_cache: true
            hibernate.id.new_generator_mappings: false
        database-platform: MYSQL
        hibernate:
            ddl-auto: update
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                fixed:
                    paths:
    mvc:
        view:
            prefix: /WEB-INF/
            suffix: .jsp
server:
    context-path: /rooms
#    port: 8443
#    server.ssl.enabled: true
#    server.ssl.key-store: keystore.p12
#    server.ssl.key-store-password: password
#    server.ssl.keyStoreType: PKCS12
#    server.ssl.keyAlias: tomcat

logging:
    level:
        ROOT: info